apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: my-app
    name: js-app
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
      protocol: TCP
