apiVersion: v1

kind: ReplicationController
metadata:
  name: myapp-rc

spec:
  replicas: 3
  selector:
    app: my-app

  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: my-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
