apiVersion: v1
kind: ReplicationController

metadata:
  name: ftps

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 20
        - containerPort: 30020
        - containerPort: 30021
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: leet
  name: ftps-service
spec:
  selector:
    app: ftps
  ports:
  - port: 21
    targetPort: 21
    name: ftp21
  - port: 20
    targetPort: 20
    name: ftp20
  - port: 30020
    targetPort: 30020
    name: ftp30020
  - port: 30021
    targetPort: 30021
    name: ftp30021
  type: LoadBalancer

#liveness prob for telegraf
