apiVersion: v1
kind: ReplicationController

metadata:
  name: ftps-rc

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - name: ftps-port
          containerPort: 21
          containerPort: 40000
          containerPort: 40001
          containerPort: 40002

---
apiVersion: v1
kind: Service
metadata:
  name: ftps-service
spec:
  selector:
    app: ftps
  ports:
    - port: 21
      targetPort: ftps-port
  type: LoadBalancer
