apiVersion: v1

kind: ReplicationController
metadata:
  name: grafana

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-img
        imagePullPolicy: Never
        ports:
        - name: grafana-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: leet
  name: grafana-service
spec:
  selector:
    app: grafana
  ports:
  - name: grafana-sp
    port: 3000
    targetPort: grafana-port
  type: LoadBalancer

# liveness prob for telegraf
