apiVersion: v1

kind: ReplicationController
metadata:
  name: influxdb

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb-img
        imagePullPolicy: Never
        ports:
        - name: influxdb-port
          containerPort: 8086
        livenessProbe:
          tcpSocket:
            port: 8086
          initialDelaySeconds: 15
        volumeMounts:
          - mountPath: /var/lib/influxdb
            name: influx-volume
      volumes:
        - name: influx-volume
          hostPath:
            path: /data/influxdb
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  ports:
  - name: influxdb-sp
    port: 8086
    targetPort: influxdb-port
  selector:
    app: influxdb

# liveness prob to ckech telegraf
