apiVersion: v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
    config: |
        adress-pools:
        - name: default
          protocol: layer2
          adresses:
          - 192.168.99.104-192.168.99.104
