apiVersion: v1

kind: ReplicationController
metadata:
  name: mysql-rc

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-img
        imagePullPolicy: Never
        ports:
        - name: mysql-port
          containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - name: mysql-sp
    port: 3306
    targetPort: mysql-port
  selector:
    app: mysql
