apiVersion: v1

kind: ReplicationController
metadata:
  name: mysql

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-img
        imagePullPolicy: Never
        ports:
        - name: mysql-port
          containerPort: 3306
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-volume
      volumes:
        - name: mysql-volume
          hostPath:
            path: /data/mysqldb
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - name: mysql-sp
    port: 3306
    targetPort: mysql-port
  selector:
    app: mysql

    # liveness prob to check telegraf
