apiVersion: v1

kind: ReplicationController
metadata:
  name: nginx

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-img
        imagePullPolicy: Never
        ports:
        - name: nginx-http
          containerPort: 80
        - name: nginx-https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: leet
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-htp
    port: 80
    targetPort: nginx-http
  - name: nginx-htps
    port: 443
    targetPort: nginx-https
  type: LoadBalancer

  #liveness prob to tech telegraf
