apiVersion: v1

kind: ReplicationController
metadata:
  name: phpmyadmin-rc

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmine-img
        imagePullPolicy: Never
        ports:
        - name: php-port
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - name: wp-sp
    port: 80
    targetPort: php-port
