apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-opp
spec:
  containers:
  - image: nginx
    name: js-app
    livenessProbe:
      httpGet:
        path: /
        port: 8080
    ports:
    - containerPort: 8080
      protocol: TCP
