apiVersion: v1
kind: Pod
metadata:
  name: wp-website
  labels:
    app: wp-pod
spec:
  containers:
  - image: wp-site
    name: wordpress
    imagePullPolicy: Never
  - image: wp-db
    name: mysql
    imagePullPolicy: Never
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
