apiVersion: v1

kind: ReplicationController
metadata:
  name: wp-rc

spec:
  replicas: 1

  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        ports:
        - name: wp-port
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: wp-service
spec:
  type: NodePort
  ports:
  - name: wp-sp
    port: 80
    targetPort: wp-port
    nodePort: 30123
  selector:
    app: worpdress
